sudo: required
services: docker
language: bash
env:
    global:
        - DOCKER_REPO=tiepie/android-build-environment
        - NDK_VERSION=r15c
        - QT_MAJOR_VERSION=5
        - QT_MINOR_VERSION=9
        - QT_RELEASE_VERSION=5
    matrix:
        - SUITE=xenial
        - SUITE=bionic

script:
    - python build.py --suite="$SUITE" --docker-repo="$DOCKER_REPO" --ndk-version="$NDK_VERSION" --qt-major-version=$QT_MAJOR_VERSION --qt-minor-version=$QT_MINOR_VERSION --qt-release-version=$QT_RELEASE_VERSION
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO:amd64-$SUITE; fi
